# docker-compose.yml (Versão Final - Segura para Produção)

services:
  # Serviço do Banco de Dados para armazenar as métricas
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=network_monitoring
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASS}
    restart: unless-stopped

  # Serviço do Painel de Visualização (Dashboard)
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${INFLUXDB_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    restart: unless-stopped

  # Serviço da nossa API que recebe os dados e envia alertas
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASS}
      - INFLUXDB_DB=network_monitoring
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped

# Define os volumes para garantir que os dados sejam persistentes
volumes:
  influxdb_data:
  grafana_data: