# Arquivo: docker-compose.yml

services:
  # --- SERVIÇOS DO SISTEMA DE MONITORAMENTO (JÁ EXISTENTES) ---
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=network_monitoring
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASS}
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${INFLUXDB_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    restart: unless-stopped

  network-api:
    build: ./api
    container_name: network-api
    # AJUSTE: Porta 5000 reativada para a API de monitoramento.
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASS}
      - INFLUXDB_DB=network_monitoring
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped

  # --- NOVOS SERVIÇOS PARA O SISTEMA DE PONTO ---

  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped

  ponto-api:
    build: ./ponto-api
    container_name: ponto-api
    volumes:
      - ./ponto-api:/app
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASS}@postgres-db:5432/${POSTGRES_DB}
    restart: unless-stopped

  ponto-frontend:
    build: ./ponto-frontend
    container_name: ponto-frontend
    # AJUSTE: O frontend agora escuta na porta 80 do servidor, recebendo o tráfego da porta 3080 externa.
    ports:
      - "80:80"
    depends_on:
      - ponto-api
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
  postgres_data: