version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=network_monitoring
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Isso-e-um-teste@ # TROQUE POR UMA SENHA FORTE
      - INFLUXDB_HTTP_LOG_ENABLED=true

  grafana:
    image: grafana/grafana-enterprise:latest # A versão enterprise é gratuita para uso
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Isso-e-um-teste@ # TROQUE POR UMA SENHA FORTE

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=sIsso-e-um-teste@ # USE A MESMA SENHA DO INFLUXDB
      - INFLUXDB_DB=network_monitoring
      - TELEGRAM_BOT_TOKEN= # Deixe em branco por agora
      - TELEGRAM_CHAT_ID=   # Deixe em branco por agora
