# Arquivo: ponto-frontend/Dockerfile
# Versão modificada para o teste de isolamento.

# Usamos a imagem oficial e leve do Nginx.
FROM nginx:1.21-alpine

# Remove a configuração padrão do Nginx.
RUN rm /etc/nginx/conf.d/default.conf

# Copia nosso arquivo de configuração personalizado.
COPY nginx.conf /etc/nginx/conf.d

# AJUSTE: Copia nossa pasta de teste 'html' para a pasta raiz do Nginx.
COPY ./html/ /usr/share/nginx/html/
