# Arquivo: ponto-frontend/Dockerfile
# Versão super simplificada para o teste "Hello, World!".

FROM nginx:1.21-alpine

# Remove a configuração padrão.
RUN rm /etc/nginx/conf.d/default.conf

# Copia nosso arquivo de configuração simplificado.
COPY nginx.conf /etc/nginx/conf.d

# Copia APENAS o nosso arquivo index.html para a pasta raiz do Nginx.
COPY index.html /usr/share/nginx/html/
